kind: pipeline
name: tests
clone:
  disable: true
trigger:
  event: push
steps:
  - name: clone
    image: proalexandr/git-lfs:2.7.2
    commands:
      - git clone https://github.com/${DRONE_REPO}.git .
      - git checkout $DRONE_COMMIT

  - name: lint
    image: node:10.16
    commands:
      - npm run lint

# TODO: Fix different font rendering on different operation systems
#  - name: cypress
#    image: cypress/included:3.3.1
#    commands:
#      - npm install
#      - npm run test:cypress:onhost

#  - name: upload-diffs
#    image: proalexandr/minio-zip:2019-05-29_3.0-r7
#    environment:
#      MC_HOST_pixelpoint:
#        from_secret: mc_host
#    commands:
#      - export DIFF_FILENAME=diff-$(date +%s).zip
#      - find cypress/snapshots -name '*.diff.png' | zip -0 $DIFF_FILENAME  -@
#      - mc cp $DIFF_FILENAME pixelpoint/kf-test-diffs/
#      - echo "You can download a diff file, https://$(echo $MC_HOST_pixelpoint | cut -d"@" -f2)/kf-test-diffs/$DIFF_FILENAME"
#    when:
#      status:
#        - failure
